In [17]:
height_in = [74, 74, 72, 75, 75, 73]
weight_lb = [180, 215, 210, 205, 190, 195]

# Import numpy
import numpy as np

In [18]:
# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_lb = np.array(weight_lb)
np_weight_kg = np_weight_lb * 0.453592

print (np_height_m)
print (np_weight_kg)

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print (bmi)
bmi > 23
light = bmi < 21
print (light)
bmi_light = bmi[light]
print(bmi_light)

[1.8796 1.8796 1.8288 1.905  1.905  1.8542]
[81.64656 97.52228 95.25432 92.98636 86.18248 88.45044]
[23.11037639 27.60406069 28.48080465 25.62295933 23.74810865 25.72686361]
[False False False False False False]
[]


In [15]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print (areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print (areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [19]:
import math

# Definition of radius
r = 0.43

# Calculate C
C = 2 * math.pi * r

# Calculate A
A = math.pi * r ** 2

# Build printout
print(f"Circumference: {C:.2f}")
print(f"Area: {A:.2f}")


Circumference: 2.70
Area: 0.58


In [22]:
import math

# شعاع دایره
r = 5

# محاسبه طول مدار دایره
C = 2 * math.pi * r

print(f'{C:.2f}')


31.42
